/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sa;

import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author SR
 */
public class Main extends javax.swing.JFrame {
    int xMouse;
    int yMouse;

    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        initilize();
    }
     private void initilize(){
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("S.png")));
     }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Header = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        MenuBar = new javax.swing.JPanel();
        M = new javax.swing.JLabel();
        me = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        STInfo = new javax.swing.JLabel();
        Course = new javax.swing.JLabel();
        Tution = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        Result = new javax.swing.JLabel();
        Trim = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 200));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(540, 350));

        jPanel1.setBackground(new java.awt.Color(38, 38, 38));
        jPanel1.setLayout(null);

        Header.setBackground(new java.awt.Color(34, 49, 63));
        Header.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                HeaderMouseDragged(evt);
            }
        });
        Header.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                HeaderMousePressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText(" X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("-");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(58, 85, 155));
        jLabel10.setText("Main Page");

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sa/image/S.png"))); // NOI18N

        javax.swing.GroupLayout HeaderLayout = new javax.swing.GroupLayout(Header);
        Header.setLayout(HeaderLayout);
        HeaderLayout.setHorizontalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(242, 242, 242)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        HeaderLayout.setVerticalGroup(
            HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HeaderLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(HeaderLayout.createSequentialGroup()
                .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(HeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel1.add(Header);
        Header.setBounds(0, 0, 540, 30);

        MenuBar.setBackground(new java.awt.Color(38, 38, 38));
        MenuBar.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        MenuBar.setForeground(new java.awt.Color(89, 89, 89));

        M.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        M.setForeground(new java.awt.Color(153, 153, 153));
        M.setText("Menu");
        M.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                MMouseMoved(evt);
            }
        });
        M.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                MMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                MMouseExited(evt);
            }
        });

        javax.swing.GroupLayout MenuBarLayout = new javax.swing.GroupLayout(MenuBar);
        MenuBar.setLayout(MenuBarLayout);
        MenuBarLayout.setHorizontalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(M, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(319, Short.MAX_VALUE))
        );
        MenuBarLayout.setVerticalGroup(
            MenuBarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuBarLayout.createSequentialGroup()
                .addComponent(M, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel1.add(MenuBar);
        MenuBar.setBounds(170, 30, 370, 20);

        me.setBackground(new java.awt.Color(38, 38, 38));
        me.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        me.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                meMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                meMouseExited(evt);
            }
        });
        me.setLayout(null);

        jLabel3.setForeground(new java.awt.Color(153, 153, 153));
        jLabel3.setText("Manage User");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jLabel3MouseExited(evt);
            }
        });
        me.add(jLabel3);
        jLabel3.setBounds(10, 20, 80, 14);

        jLabel4.setForeground(new java.awt.Color(153, 153, 153));
        jLabel4.setText("Logout");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel4MouseEntered(evt);
            }
        });
        me.add(jLabel4);
        jLabel4.setBounds(10, 70, 60, 20);

        jLabel13.setForeground(new java.awt.Color(153, 153, 153));
        jLabel13.setText("User Table");
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jLabel13MouseEntered(evt);
            }
        });
        me.add(jLabel13);
        jLabel13.setBounds(10, 46, 70, 20);

        jPanel1.add(me);
        me.setBounds(180, 48, 110, 0);

        STInfo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        STInfo.setForeground(new java.awt.Color(102, 255, 255));
        STInfo.setText("Student Information");
        STInfo.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        STInfo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                STInfoMouseClicked(evt);
            }
        });
        jPanel1.add(STInfo);
        STInfo.setBounds(250, 60, 180, 30);

        Course.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Course.setForeground(new java.awt.Color(102, 255, 255));
        Course.setText("Courses");
        Course.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        Course.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CourseMouseClicked(evt);
            }
        });
        jPanel1.add(Course);
        Course.setBounds(250, 160, 77, 30);

        Tution.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Tution.setForeground(new java.awt.Color(102, 255, 255));
        Tution.setText("Tuition Fee");
        Tution.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        Tution.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TutionMouseClicked(evt);
            }
        });
        jPanel1.add(Tution);
        Tution.setBounds(250, 110, 110, 30);

        jPanel4.setBackground(new java.awt.Color(52, 73, 94));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sa/image/SIS.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(103, 103, 103)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(120, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4);
        jPanel4.setBounds(0, 30, 170, 330);

        Result.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Result.setForeground(new java.awt.Color(102, 255, 255));
        Result.setText("Result");
        Result.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        Result.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ResultMouseClicked(evt);
            }
        });
        jPanel1.add(Result);
        Result.setBounds(250, 210, 60, 30);

        Trim.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        Trim.setForeground(new java.awt.Color(102, 255, 255));
        Trim.setText("Trimester");
        Trim.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(51, 51, 51), new java.awt.Color(51, 51, 51)));
        Trim.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TrimMouseClicked(evt);
            }
        });
        jPanel1.add(Trim);
        Trim.setBounds(250, 260, 90, 30);

        jLabel14.setForeground(new java.awt.Color(0, 153, 153));
        jLabel14.setText("Copyright©SIS Soft || All rights reserved");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(230, 330, 220, 14);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 541, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
        
    }//GEN-LAST:event_jLabel2MouseClicked

    private void HeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMouseDragged
        // TODO add your handling code here:
        
         int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_HeaderMouseDragged

    private void HeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_HeaderMousePressed
        // TODO add your handling code here:
        
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_HeaderMousePressed

    private void MMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MMouseEntered
        // TODO add your handling code here:
        me.setSize(95,105);
    }//GEN-LAST:event_MMouseEntered

    private void MMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MMouseExited
        // TODO add your handling code here:
        //me.setSize(0,0);
    }//GEN-LAST:event_MMouseExited

    private void meMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meMouseEntered
        // TODO add your handling code here:
        me.setSize(95,105);
    }//GEN-LAST:event_meMouseEntered

    private void meMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_meMouseExited
        // TODO add your handling code here:
        me.setSize(0,0);
    }//GEN-LAST:event_meMouseExited

    private void MMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MMouseMoved
        // TODO add your handling code here:
        M.setBackground(Color.blue);
    }//GEN-LAST:event_MMouseMoved

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        Login l=new Login();
        l.setVisible(true);
        l.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseEntered
        // TODO add your handling code here:
        me.setSize(95,105);
        
    }//GEN-LAST:event_jLabel4MouseEntered

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        UManage m=new UManage();
        m.setVisible(true);
        m.setLocationRelativeTo(this);
        this.dispose();
        
        
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseEntered
        // TODO add your handling code here:
         me.setSize(95,105);
        
    }//GEN-LAST:event_jLabel3MouseEntered

    private void jLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseExited
        // TODO add your handling code here:
         me.setSize(0,0);
    }//GEN-LAST:event_jLabel3MouseExited

    private void STInfoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_STInfoMouseClicked
        // TODO add your handling code here:
        SInfo s=new SInfo();
        s.setVisible(true);
        s.setLocationRelativeTo(this);
        this.dispose();
        
    }//GEN-LAST:event_STInfoMouseClicked

    private void CourseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CourseMouseClicked
        // TODO add your handling code here:
        Course cs =new Course();
        cs.setVisible(true);
        cs.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_CourseMouseClicked

    private void TutionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TutionMouseClicked
        // TODO add your handling code here:
        Tuition t=new Tuition();
        t.setVisible(true);
        t.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_TutionMouseClicked

    private void ResultMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ResultMouseClicked
        // TODO add your handling code here:
       /* Result rs=new Result();
        rs.setVisible(true);
        rs.setLocationRelativeTo(this);
       this.setState(JFrame.ICONIFIED);
        */
    }//GEN-LAST:event_ResultMouseClicked

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        // TODO add your handling code here:
        UserTable ut =new UserTable();
        ut.setVisible(true);
        //this.setVisible(true);
        
        
        
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel13MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseEntered
        // TODO add your handling code here:
        me.setSize(95,105);
        
    }//GEN-LAST:event_jLabel13MouseEntered

    private void TrimMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TrimMouseClicked
        // TODO add your handling code here:
        Trimester trm=new Trimester();
        trm.setVisible(true);
        this.dispose();
        trm.setLocationRelativeTo(this);
        
    }//GEN-LAST:event_TrimMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Course;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel M;
    private javax.swing.JPanel MenuBar;
    private javax.swing.JLabel Result;
    private javax.swing.JLabel STInfo;
    private javax.swing.JLabel Trim;
    private javax.swing.JLabel Tution;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel me;
    // End of variables declaration//GEN-END:variables
}
