/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sa;

import java.awt.Toolkit;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import oracle.jdbc.OraclePreparedStatement;
import oracle.jdbc.OracleResultSet;

/**
 *
 * @author SR
 */
public class UManage extends javax.swing.JFrame {
    int xMouse;
    int yMouse;
    /**
     * Creates new form UManage
     */
        Connection con=null;                
        PreparedStatement ps =null;
        ResultSet rs=null;
    public UManage() {
        initComponents();
        JL1.setVisible(false);
        JL2.setVisible(false);
        JL3.setVisible(false);
        initilize();
    }
    private void initilize(){
        this.setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("S.png")));
     }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Add = new javax.swing.JButton();
        Elete = new javax.swing.JButton();
        UInfo = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        UId = new javax.swing.JTextField();
        UN = new javax.swing.JTextField();
        Pass = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        Search = new javax.swing.JTextField();
        JL1 = new javax.swing.JLabel();
        JL2 = new javax.swing.JLabel();
        JL3 = new javax.swing.JLabel();
        Refresh = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(350, 200));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(38, 38, 38));
        jPanel1.setLayout(null);

        Add.setText("Add user");
        Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddActionPerformed(evt);
            }
        });
        jPanel1.add(Add);
        Add.setBounds(50, 246, 90, 23);

        Elete.setText("Delete User");
        Elete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EleteActionPerformed(evt);
            }
        });
        jPanel1.add(Elete);
        Elete.setBounds(360, 246, 110, 23);

        UInfo.setText("Update user Info");
        UInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UInfoActionPerformed(evt);
            }
        });
        jPanel1.add(UInfo);
        UInfo.setBounds(180, 246, 140, 23);

        jLabel3.setForeground(new java.awt.Color(204, 204, 204));
        jLabel3.setText("User ID");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(150, 60, 50, 14);

        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("User Name");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(150, 120, 70, 14);

        jLabel5.setForeground(new java.awt.Color(204, 204, 204));
        jLabel5.setText("Password");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(150, 170, 70, 14);
        jPanel1.add(UId);
        UId.setBounds(250, 50, 120, 30);

        UN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UNActionPerformed(evt);
            }
        });
        jPanel1.add(UN);
        UN.setBounds(250, 106, 120, 30);

        Pass.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassActionPerformed(evt);
            }
        });
        jPanel1.add(Pass);
        Pass.setBounds(250, 160, 120, 30);

        jLabel6.setForeground(new java.awt.Color(204, 204, 204));
        jLabel6.setText("Search");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 10, 50, 14);

        Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchActionPerformed(evt);
            }
        });
        Search.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                SearchKeyReleased(evt);
            }
        });
        jPanel1.add(Search);
        Search.setBounds(90, 10, 110, 30);

        JL1.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        JL1.setForeground(new java.awt.Color(255, 0, 0));
        JL1.setText("Id can not be empty");
        jPanel1.add(JL1);
        JL1.setBounds(256, 88, 95, 15);

        JL2.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        JL2.setForeground(new java.awt.Color(255, 0, 0));
        JL2.setText("User Name  can not be empty");
        jPanel1.add(JL2);
        JL2.setBounds(250, 146, 143, 15);

        JL3.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        JL3.setForeground(new java.awt.Color(255, 0, 0));
        JL3.setText("Password can not be empty");
        jPanel1.add(JL3);
        JL3.setBounds(250, 200, 140, 15);

        Refresh.setText("Refresh");
        Refresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RefreshActionPerformed(evt);
            }
        });
        jPanel1.add(Refresh);
        Refresh.setBounds(395, 10, 90, 23);

        jLabel10.setForeground(new java.awt.Color(0, 153, 153));
        jLabel10.setText("Copyright©SIS Soft | All rights reserved");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(160, 350, 210, 20);

        jPanel2.setBackground(new java.awt.Color(34, 49, 63));
        jPanel2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jPanel2MouseDragged(evt);
            }
        });
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jPanel2MousePressed(evt);
            }
        });
        jPanel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(204, 204, 204));
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel1);
        jLabel1.setBounds(485, 6, 11, 26);

        jLabel2.setFont(new java.awt.Font("Dialog", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 204, 204));
        jLabel2.setText("-");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel2);
        jLabel2.setBounds(461, 6, 12, 20);

        jLabel8.setForeground(new java.awt.Color(153, 255, 51));
        jLabel8.setText("User Manage Panel");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(60, 10, 120, 14);

        jLabel12.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(204, 204, 204));
        jLabel12.setText("<");
        jLabel12.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel12MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel12);
        jLabel12.setBounds(430, 10, 20, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/sa/image/S.png"))); // NOI18N
        jPanel2.add(jLabel9);
        jLabel9.setBounds(10, 0, 30, 30);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 510, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setState(JFrame.ICONIFIED);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddActionPerformed
        // TODO add your handling code here:
        con=DBConnect.Connect();
        JL1.setVisible(false);
        JL2.setVisible(false);
        JL3.setVisible(false);
        
        try{
             if(UId.getText().equals(""))
        {
            JL1.setVisible(true);
        }
       else if(UN.getText().equals(""))
        {
            JL2.setVisible(true);
        }
        else if(Pass.getText().equals(""))
        {
            JL3.setVisible(true);
        }
             else{
                String sql ="insert into Admin(Id,name,Password)values(?,?,?)";
                
                
                ps = (PreparedStatement)(PreparedStatement)con.prepareStatement(sql);
                ps.setString(1,UId.getText());
                ps.setString(2,UN.getText());
                ps.setString(3,Pass.getText());
                rs=(ResultSet)(ResultSet)ps.executeQuery();
                 if(rs.next()){
                     
                    JOptionPane.showMessageDialog(null," User successfully added ! ");
                     
                 }
                 
                
                }
            
            
    
    }catch(Exception e){
    
    JOptionPane.showMessageDialog(null,"User already exist!");
    
    
    }
        
        
        
        
        
        
        
    }//GEN-LAST:event_AddActionPerformed

    private void EleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EleteActionPerformed
        // TODO add your handling code here:
        
        con=DBConnect.Connect();
        int p= JOptionPane.showConfirmDialog(null,"Do you Really want to delete","Delete",JOptionPane.YES_NO_OPTION);
        if(p==0){
        try{
            
            String sql="Delete from Admin where id =?";
            ps=(PreparedStatement) con.prepareStatement(sql);
            ps.setString(1,UId.getText());
        ps.execute();
        JOptionPane.showMessageDialog(null,"Deleted");
        
        }catch(Exception e){
        
        JOptionPane.showMessageDialog(null," ");
        
        }
      
                }
        
    }//GEN-LAST:event_EleteActionPerformed

    private void UNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UNActionPerformed

    private void jPanel2MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseDragged
        // TODO add your handling code here:
         int x=evt.getXOnScreen();
        int y=evt.getYOnScreen();
        this.setLocation(x-xMouse,y-yMouse);
    }//GEN-LAST:event_jPanel2MouseDragged

    private void jPanel2MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MousePressed
        // TODO add your handling code here:
        xMouse=evt.getX();
        yMouse=evt.getY();
    }//GEN-LAST:event_jPanel2MousePressed

    private void PassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassActionPerformed

    private void SearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_SearchKeyReleased
        // TODO add your handling code here:
        con=DBConnect.Connect();
        try{
            String sql ="select *from Admin where Id=?";
                
                
                ps =(PreparedStatement) con.prepareStatement(sql);
                ps.setString(1,Search.getText());
                rs=(ResultSet) ps.executeQuery();
                if(rs.next()){
                
                String add1 = rs.getString("Id");
                UId.setText(add1);
                String add2 = rs.getString("name");
                UN.setText(add2);
                String add3 = rs.getString("Password");
                Pass.setText(add3);
                
                
               
                }
                
        }
        catch(Exception e){
        
        JOptionPane.showMessageDialog(null," ");
        
        }
    }//GEN-LAST:event_SearchKeyReleased

    private void RefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RefreshActionPerformed
        // TODO add your handling code here:
        Search.setText("");
        UId.setText("");
        UN.setText("");
        Pass.setText("");
        
    }//GEN-LAST:event_RefreshActionPerformed

    private void UInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UInfoActionPerformed
        // TODO add your handling code here:
          con=DBConnect.Connect();
          int p= JOptionPane.showConfirmDialog(null,"Do you Really want to Update?","Update",JOptionPane.YES_NO_OPTION);
          if(p==0){
          try{
              //String  value1= UId.getText();
              String  value2= UN.getText();
              String  value3= Pass.getText();
          
              String sql="Update Admin set name='"+value2+"',Password='"+value3+"'"
                      + "where Id=? ";
              ps =(PreparedStatement) con.prepareStatement(sql);
              ps.setString(1,UId.getText());
               rs=(ResultSet) ps.executeQuery();
               
               JOptionPane.showMessageDialog(null, "Updated! ");
              
          
          
          }catch(Exception e){
          JOptionPane.showMessageDialog(null,e);
          
          }
         }
        
    }//GEN-LAST:event_UInfoActionPerformed

    private void jLabel12MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel12MouseClicked
        // TODO add your handling code here:
        
        Main m=new Main();
        m.setVisible(true);
        m.setLocationRelativeTo(this);
        this.dispose();
    }//GEN-LAST:event_jLabel12MouseClicked

    private void SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UManage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UManage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Add;
    private javax.swing.JButton Elete;
    private javax.swing.JLabel JL1;
    private javax.swing.JLabel JL2;
    private javax.swing.JLabel JL3;
    private javax.swing.JPasswordField Pass;
    private javax.swing.JButton Refresh;
    private javax.swing.JTextField Search;
    private javax.swing.JTextField UId;
    private javax.swing.JButton UInfo;
    private javax.swing.JTextField UN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
